const Invoice = {
    async generate(booking) {
        const customer = booking.customerId ? await db.customers.get(booking.customerId) : null;
        const businessName = await Utils.getSetting('businessName', 'My Car Wash');
        const businessAddress = await Utils.getSetting('businessAddress', 'Sheffield, UK');
        const businessPhone = await Utils.getSetting('businessPhone', '');

        const invoiceNum = 'WP-' + Date.now().toString(36).toUpperCase();
        const date = Utils.formatDate(new Date());

        const html = `
            <div style="font-family:Arial,sans-serif;max-width:400px;margin:0 auto;padding:20px;">
                <div style="text-align:center;margin-bottom:24px;">
                    <h1 style="margin:0;font-size:24px;color:#000;">${Utils.escapeHTML(businessName)}</h1>
                    <p style="margin:4px 0 0;color:#8e8e93;font-size:13px;">${Utils.escapeHTML(businessAddress)}${businessPhone ? ' · ' + Utils.escapeHTML(businessPhone) : ''}</p>
                </div>
                <hr style="border:none;border-top:1px solid #e5e5ea;margin:16px 0;">
                <div style="display:flex;justify-content:space-between;font-size:14px;margin-bottom:16px;">
                    <div>
                        <strong>Invoice ${invoiceNum}</strong><br>
                        <span style="color:#8e8e93;">${date}</span>
                    </div>
                    <div style="text-align:right;">
                        <strong>Bill To:</strong><br>
                        <span>${Utils.escapeHTML(booking.customerName || customer?.name || 'N/A')}</span><br>
                        <span style="color:#8e8e93;font-size:13px;">${Utils.escapeHTML(booking.address || customer?.address || '')}</span>
                    </div>
                </div>
                <table style="width:100%;font-size:14px;border-collapse:collapse;margin-bottom:16px;">
                    <thead>
                        <tr style="border-bottom:2px solid #000;">
                            <th style="text-align:left;padding:8px 0;">Service</th>
                            <th style="text-align:right;padding:8px 0;">Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr style="border-bottom:1px solid #e5e5ea;">
                            <td style="padding:8px 0;">Exterior Wash & Protect</td>
                            <td style="text-align:right;padding:8px 0;">${Utils.formatCurrency(booking.price || 0)}</td>
                        </tr>
                    </tbody>
                    <tfoot>
                        <tr style="border-top:2px solid #000;font-weight:700;">
                            <td style="padding:8px 0;">Total</td>
                            <td style="text-align:right;padding:8px 0;">${Utils.formatCurrency(booking.price || 0)}</td>
                        </tr>
                    </tfoot>
                </table>
                <div style="text-align:center;font-size:12px;color:#8e8e93;margin-top:24px;">
                    <p>Thank you for your business</p>
                    <p>Generated by WashPilot</p>
                </div>
            </div>
        `;

        await db.invoices.put({
            id: Utils.generateId(),
            bookingId: booking.id,
            customerId: booking.customerId,
            invoiceNum,
            date: new Date(),
            amount: booking.price || 0,
            customerName: booking.customerName || customer?.name || ''
        });

        Utils.showModal('Invoice', `
            <div style="background:white;border-radius:8px;padding:8px;margin-bottom:12px;">${html}</div>
            <button class="btn btn-primary" id="inv-share">Share Invoice</button>
        `);

        document.getElementById('inv-share').addEventListener('click', () => {
            if (navigator.share) {
                navigator.share({
                    title: `Invoice ${invoiceNum}`,
                    text: `Invoice from ${businessName}\nTotal: ${Utils.formatCurrency(booking.price || 0)}`
                });
            } else {
                Utils.toast('Invoice saved — share manually');
            }
        });
    },

    async renderList(container) {
        const invoices = await db.invoices.toArray();
        let listHTML = '';
        if (invoices.length === 0) {
            listHTML = `<div class="empty-state"><div class="empty-state-icon">${icon('file-text')}</div><div class="empty-state-text">No invoices yet</div></div>`;
        } else {
            listHTML = invoices.sort((a, b) => new Date(b.date) - new Date(a.date)).map(inv => `
                <div class="list-item">
                    <div class="list-icon brand">${icon('file-text')}</div>
                    <div class="list-content">
                        <div class="list-title">${Utils.escapeHTML(inv.invoiceNum)}</div>
                        <div class="list-subtitle">${Utils.escapeHTML(inv.customerName || 'N/A')} · ${Utils.formatDate(inv.date)}</div>
                    </div>
                    <div class="list-right"><div class="list-amount income">${Utils.formatCurrency(inv.amount)}</div></div>
                </div>
            `).join('');
        }

        container.innerHTML = `
            <div style="padding:var(--sp-5);">
                <h2 style="font-size:22px;font-weight:700;letter-spacing:-0.4px;margin-bottom:var(--sp-5);">Invoices</h2>
                <div class="card">${listHTML}</div>
            </div>
        `;
    }
};
